language: ruby
rvm:
  - 1.8.7
  - 1.9.3
gemfile: src/Gemfile
env: 
  - SUITE=spec
install:
  - bundle install
script:
  - rake $SUITE
branches:
  only:
    - rpm-task-fix
notifications:
  irc:
    channels:
      - "irc.freenode.org#aeolus"
    use_notice: true
    skip_join: false
